package com.hsy.warehouse_manager2;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.transaction.annotation.EnableTransactionManagement;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
//mapper接口扫描包,指明mapper接口所在包，自动生成mapper接口代理对象并假如ioc容器中

//开启缓存
@EnableCaching
@MapperScan(basePackages = "com.hsy.warehouse_manager2.mapper")
@SpringBootApplication
@EnableTransactionManagement
public class WarehouseManager2Application {

    public static void main(String[] args) {
        SpringApplication.run(WarehouseManager2Application.class, args);
    }

}
